### PR TITLE
Issue 18: Housekeeping shouldn't fail when attempting to cleanup a path that is already deleted

### LINKED ISSUE #18: Housekeeping fails when s3 location is deleted
If S3 location is deleted, and hk record is not deleted. When hk tries to delete the s3 file/folder it fails.

Suggested approach:- Check the s3 location exists, if exists then delete, else avoid deletion. Then delete record from hk

### PR DESCRIPTION
**Pull request by courtsVII**
Fixes #18

### CODE REVIEW

File: src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java [hunk 1]
```diff
@@ -47,39 +48,65 @@ public FileSystemHousekeepingService(LegacyReplicaPathRepository legacyReplicaPa
     LOG.warn("{}.fixIncompleteRecord(LegacyReplicaPath) should be removed in future.", getClass());
   }
 
+  private FileSystem fileSystemForPath(LegacyReplicaPath cleanUpPath) {
+    LOG.info("Attempting to delete path '{}' from file system", cleanUpPath);
```
Comment (massdosage) [inline src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: This isn't doing a delete? Update comment to clarify that this is trying to determine the FS for a path, or just remove it. If you do decide to keep it it's probably worth putting on debug rather than info.

File: src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java [hunk 2]
```diff
@@ -47,39 +48,65 @@ public FileSystemHousekeepingService(LegacyReplicaPathRepository legacyReplicaPa
...
+    Path path = new Path(cleanUpPath.getPath());
+    FileSystem fs;
+    try {
+      fs = path.getFileSystem(conf);
```
Comment (massdosage) [inline src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: You could just return this and then you don't even need the "fs" variable. The scope expanding out on line 54 definitely isn't needed.

File: src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java [hunk 3]
```diff
@@ -47,39 +48,65 @@ public FileSystemHousekeepingService(LegacyReplicaPathRepository legacyReplicaPa
     LOG.warn("{}.fixIncompleteRecord(LegacyReplicaPath) should be removed in future.", getClass());
   }
 
+  private FileSystem fileSystemForPath(LegacyReplicaPath cleanUpPath) {
+    LOG.info("Attempting to delete path '{}' from file system", cleanUpPath);
+    Path path = new Path(cleanUpPath.getPath());
```
Comment (massdosage) [inline src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: This method could take the Path type directly so you don't have to create it twice (once here and once in the calling method currently)

Comment (courtsVII) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: Done

File: src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java (hunk 2 above)
Comment (courtsVII) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: Done

File: src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java (hunk 1 above)
Comment (courtsVII) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: Moved it to more relevant place, aftermath of copy and paste :)

File: src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java [hunk 4]
```diff
@@ -47,39 +48,62 @@ public FileSystemHousekeepingService(LegacyReplicaPathRepository legacyReplicaPa
...
+          LOG.info("Deleting path '{}' from housekeeping database", cleanUpPath);
+          legacyReplicaPathRepository.delete(cleanUpPath);
+        } catch (ObjectOptimisticLockingFailureException e) {
+          LOG.debug(
+              "Failed to delete path '{}': probably already cleaned up by process running at same time. Ok to ignore. {}",
+              cleanUpPath, e.getMessage());
+        }
+      }
+    } catch (Exception e) {
+      LOG.warn("Path '{}' was not deleted from the housekeeping database. {}", cleanUpPath, e.getMessage());
```
Comment (patduin) [inline src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: This does prevent housekeeping from failing but it won't delete the path from the repo, so we'll get this warning on every run of housekeeping or am I missing something?

Comment (courtsVII) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: This block is only reached if `legacyReplicaPathRepository.delete(cleanUpPath);` fails, signifying a failure to delete the specified path from the Housekeeping database

Comment (patduin) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: if `oneOfMySiblingsWillTakeCareOfMyAncestors(path, rootPath, fs) || thereIsNothingMoreToDelete(fs, rootPath)` throws an exception which I thought was why we got the error in the first place, we'll hit the catch

Comment (courtsVII) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: Ah right, I was looking at wrong try block.. I'm hesitant to delete data from the Housekeeping database here as it may fail for another unforeseen reason that isn't the path being deleted already, do you think we should just do the deletion anyway?

Comment (patduin) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: I guess we need to know exactly at what point we got the error and check what path we were trying to delete is that some parent path or something else? What would happen if we warn and run again, failure at same place?

Comment (courtsVII) [reply src/main/java/com/hotels/housekeeping/service/impl/FileSystemHousekeepingService.java]: This becomes complex cause of eventual consistency and the likes, I would rather leave it like this, they will get a small warning in their logs when they run their application but I would rather that over leaving behind data that I may be paying for
